### ISSUE TITLE
ObjcUnserializationScanner 查找__text节的兼容性。

### ISSUE THREAD

**Issue by lfiona** [Soulghost/iblessing#5]
首先先表达下敬意，unicorn的方式去做iOS静态检测的方案太赞了，我在测试时发现一个很小的问题，就是APP的代码段的名字有时候不是__TEXT，所以在查找__text节区时是不是不去判断段的名称兼容性会更好？
![image](https://user-images.githubusercontent.com/6142112/100986281-f3ad2580-3587-11eb-9aba-8459626af7f3.png)
其实在初始化的查找__text节区的时候就没有判断段的名称。
PredicateScanner也是这种情况。

**Comment by Soulghost** [comment]
收到，我之前在处理静态库的时候也遇到了类似的问题，十分感谢您的反馈，我这周末做一下优化。

**Comment by Soulghost** [comment]
已修复，https://github.com/Soulghost/iblessing/releases/tag/v0.5.1-beta
