### ISSUE TITLE
Can not get full detail from app scan

### ISSUE THREAD

**Issue by kaze-nomamani** [Soulghost/iblessing#6]
Run below command to scan app info, but iblessing will end before complete scans. 

I assume when iblessing completed scan, message "[*] write report to path" will be displayed, but scanning photo app from ios will end without reaching to "[*] write report to path"

Is this intended? 

------------------------

./iblessing-darwin -m scan -i app-info -f ~/pentest/ipa/ipa/Payload-photo/MobileSlideShow.app -o photo 

[*] Bundle Identifier: com.apple.mobileslideshow
[+] find app deeplinks
 |-- photos://
 |-- photos-navigation://
 |-- photos-event://
 |-- photos-migrate-iphoto://
 |-- com.apple.mobileslideshow://
 |-- photos-redirect://
[+] find 1830 string literals in binary
[*] process with string literals, this maybe take some time
[+] find self deeplinks URLs:
 |-- photos://album?name=favorites
 |-- photos://memory?identifier=%@
 |-- photos://places
 |-- photos://oneyearago
 |-- photos://album?uuid=%@
 |-- photos://contentmode?id=search
 |-- photos://asset?uuid=%@
 |-- photos://album?name=%@
 |-- photos://people
 |-- photos://lastasset
 |-- photos://contentmode?id=%@
 |-- photos://contentmode?id=photo-stream

----------------------------------------

**Comment by Soulghost** [comment]
Apologies for the Late Reply, it seems that there is no urls starting with http(s) in this app, so we don't need to write these urls into file.
